# Exported from Render on 2024-06-12T14:23:52Z
services:
- type: web
  name: online_bookstore
  runtime: ruby
  repo: https://github.com/chanchal-ch0udhary/Online_bookstore
  plan: free
  envVars:
  - key: RAILS_MASTER_KEY
    sync: false
  - key: WEB_CONCURRENCY
    sync: false
  - key: DATABASE_URL
    sync: false
  region: oregon
  buildCommand: ./bin/render-build.sh
  startCommand: bundle exec rails server
version: "1"

# databases:
#   - name: onlinebBookstore
#     databaseName: online_bookstore
#     user: online_user
#     plan: free

# services:
#   - type: web
#     name: onlinebBookstore
#     runtime: ruby
#     plan: free
#     buildCommand: "./bin/render-build.sh"
#     # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
#     startCommand: "bundle exec rails server"
#     envVars:
#       - key: DATABASE_URL
#         fromDatabase:
#           name: onlinebBookstore
#           property: connectionString
#       - key: RAILS_MASTER_KEY
#         sync: false
#       - key: WEB_CONCURRENCY
#         value: 2 # sensible default

